#ifndef pac5110Enums_h
#define pac5110Enums_h

enum merak_VALUE_TYPE
{
Phase_1_line_to_neutral_volts = 0x0000,   //Phase 1 line to neutral volts.
Phase_2_line_to_neutral_volts = 0x0002,   //Phase 2 line to neutral volts.
Phase_3_line_to_neutral_volts = 0x0004,   //Phase 3 line to neutral volts.
Phase_1_current = 0x0006,   //Phase 1 current.
Phase_2_current = 0x0008,   //Phase 2 current.
Phase_3_current = 0x000A,   //Phase 3 current.
Phase_1_active_power = 0x000C,   //Phase 1 active power.
Phase_2_active_power = 0x000E,   //Phase 2 active power.
Phase_3_active_power = 0x0010,   //Phase 3 active power.
Phase_1_reactive_power = 0x0012,   //Phase 1 reactive power.
Phase_2_reactive_power = 0x0014,   //Phase 2 reactive power.
Phase_3_reactive_power = 0x0016,   //Phase 3 reactive power.
Phase_1_apparent_power = 0x0018,   //Phase 1 apparent power.
Phase_2_apparent_power = 0x001A,   //Phase 2 apparent power.
Phase_3_apparent_power = 0x001C,   //Phase 3 apparent power.
Phase_1_power_factor_1 = 0x001E,   //Phase 1 power factor (1).
Phase_2_power_factor_1 = 0x0020,   //Phase 2 power factor (1).
Phase_3_power_factor_1 = 0x0022,   //Phase 3 power factor (1).
Phase_1_phase_angle = 0x0024,   //Phase 1 phase angle.
Phase_2_phase_angle = 0x0026,   //Phase 2 phase angle.
Phase_3_phase_angle = 0x0028,   //Phase 3 phase angle.
Line_1_to_Line_2_volts = 0x002A,   //Line 1 to Line 2 volts.
Line_2_to_Line_3_volts = 0x002C,   //Line 2 to Line 3 volts.
Line_3_to_Line_1_volts = 0x002E,   //Line 3 to Line 1 volts.
Frequency_of_supply_voltages = 0x0030,   //Frequency of supply voltages.
Total_system_active_power = 0x0032,   //Total system active power.
Total_system_reactive_power = 0x0034,   //Total system reactive power.
Total_system_apparent_power = 0x0036,   //Total system apparent power.
Total_system_power_factor_1 = 0x0038,   //Total system power factor (1).
Total_system_phase_angle = 0x003A,   //Total system phase angle.
Sum_of_line_currents = 0x003C,   //Sum of line currents.
Average_line_to_neutral_volts = 0x003E,   //Average line to neutral volts.
Average_line_to_line_volts = 0x0040,   //Average line to line volts.
Average_line_current = 0x0042,   //Average line current.
Neutral_current = 0x0044,   //Neutral current.
Nature_of_the_system_load = 0x0054,   //Nature of the system load
Voltage_phase_sequence = 0x0058,   //Voltage phase sequence
Current_phase_sequence = 0x005C,   //Current phase sequence
Phase_1_displacement_power_factor = 0x0060,   //Phase 1 displacement power factor
Phase_2_displacement_power_factor = 0x0062,   //Phase 2 displacement power factor
Phase_3_displacement_power_factor = 0x0064,   //Phase 3 displacement power factor
Total_displacement_power_factor = 0x0066,   //Total displacement power factor
L1_voltage_crest_factor = 0x006E,   //L1 voltage crest factor
L2_voltage_crest_factor = 0x0070,   //L2 voltage crest factor
L3_voltage_crest_factor = 0x0072,   //L3 voltage crest factor
L1_current_K_factor = 0x0074,   //L1 current K factor
L2_current_K_factor = 0x0076,   //L2 current K factor
L3_current_K_factor = 0x0078,   //L3 current K factor
Negative_sequence_unbalance_of_voltage = 0x007A,   //Negative-sequence unbalance of voltage
Zero_sequence_unbalance_of_voltage = 0x007C,   //Zero-sequence unbalance of voltage
Negative_sequence_unbalance_of_current = 0x007E,   //Negative-sequence unbalance of current
Zero_sequence_unbalance_of_current = 0x0080,   //Zero-sequence unbalance of current
Phase_1_voltage_THD_2 = 0x0082,   //Phase 1 voltage THD (2).
Phase_2_voltage_THD_2 = 0x0084,   //Phase 2 voltage THD (2).
Phase_3_voltage_THD_2 = 0x0086,   //Phase 3 voltage THD (2).
Phase_1_current_THD = 0x0088,   //Phase 1 current THD
Phase_2_current_THD = 0x008A,   //Phase 2 current THD
Phase_3_current_THD = 0x008C,   //Phase 3 current THD
Average_voltage_THD_2 = 0x008E,   //Average voltage THD (2).
Average_line_current_THD = 0x0090,   //Average line current THD.
Total_system_active_power_demand_3 = 0x0092,   //Total system active power demand (3).
Total_system_reactive_power_demand_3 = 0x0094,   //Total system reactive power demand (3).
Total_system_apparent_power_demand = 0x0096,   //Total system apparent power demand.
Phase_1_current_demand = 0x0098,   //Phase 1 current demand.
Phase_2_current_demand = 0x009A,   //Phase 2 current demand.
Phase_3_current_demand = 0x009C,   //Phase 3 current demand.
Neutral_current_demand = 0x00A2,   //Neutral current demand.
Import_active_power_demand = 0x00A4,   //Import active power demand
Export_active_power_demand = 0x00A6,   //Export active power demand
Maximum_total_system_active_power_demand_3 = 0x00A8,   //Maximum total system active power demand (3).
Maximum_total_system_reactive_power_demand_3 = 0x00AA,   //Maximum total system reactive power demand (3).
Maximum_total_system_apparent_power_demand = 0x00AC,   //Maximum total system apparent power demand.
Maximum_phase_1_current_demand = 0x00AE,   //Maximum phase 1 current demand.
Maximum_phase_2_current_demand = 0x00B0,   //Maximum phase 2 current demand.
Maximum_phase_3_current_demand = 0x00B2,   //Maximum phase 3 current demand.
Maximum_neutral_current_demand = 0x00B8,   //Maximum neutral current demand.
Maximum_import_active_power_demand = 0x0134,   //Maximum import active power demand
Maximum_export_active_power_demand = 0x01B0,   //Maximum export active power demand
Voltage_2st_63st_Harmonic_L1_2 = 0x022C,   //Voltage 2st~63st Harmonic L1 (2).
Voltage_2st_63st_Harmonic_L2_2 = 0x02A8,   //Voltage 2st~63st Harmonic L2 (2).
Voltage_2st_63st_Harmonic_L3_2 = 0x0324,   //Voltage 2st~63st Harmonic L3 (2).
Current_2st_63st_Harmonic_L1 = 0x043C,   //Current 2st~63st Harmonic L1
Current_2st_63st_Harmonic_L2 = 0x043E,   //Current 2st~63st Harmonic L2
Current_2st_63st_Harmonic_L3 = 0x0440,   //Current 2st~63st Harmonic L3
Maximum_value_of_total_active_power = 0x0442,   //Maximum value of total active power
Maximum_value_of_total_reactive_power = 0x0444,   //Maximum value of total reactive power
Maximum_value_of_total_apparent_power = 0x0446,   //Maximum value of total apparent power
Maximum_of_the_total_power_factor = 0x0448,   //Maximum of the total power factor
Maximum_value_of_L1_active_power = 0x044A,   //Maximum value of L1 active power
Maximum_value_of_L2_active_power = 0x044C,   //Maximum value of L2 active power
Maximum_value_of_L3_active_power = 0x044E,   //Maximum value of L3 active power
Maximum_value_of_L1_reactive_power = 0x0450,   //Maximum value of L1 reactive power
Maximum_value_of_L2_reactive_power = 0x0452,   //Maximum value of L2 reactive power
Maximum_value_of_L3_reactive_power = 0x0454,   //Maximum value of L3 reactive power
Maximum_value_of_L1_apparent_power = 0x0456,   //Maximum value of L1 apparent power
Maximum_value_of_L2_apparent_power = 0x0458,   //Maximum value of L2 apparent power
Maximum_value_of_L3_apparent_power = 0x045A,   //Maximum value of L3 apparent power
Maximum_of_the_L1_power_factor = 0x045C,   //Maximum of the L1 power factor
Maximum_of_the_L2_power_factor = 0x045E,   //Maximum of the L2 power factor
Maximum_of_the_L3_power_factor = 0x0460,   //Maximum of the L3 power factor
Maximum_value_of_L1_current = 0x0462,   //Maximum value of L1 current
Maximum_value_of_L2_current = 0x0464,   //Maximum value of L2 current
Maximum_value_of_L3_current = 0x0466,   //Maximum value of L3 current
Maximum_value_of_neutral_current = 0x0468,   //Maximum value of neutral current
Maximum_value_of_total_current = 0x046A,   //Maximum value of total current
Maximum_value_of_L1_voltage = 0x046C,   //Maximum value of L1 voltage
Maximum_value_of_L2_voltage = 0x046E,   //Maximum value of L2 voltage
Maximum_value_of_L3_voltage = 0x0470,   //Maximum value of L3 voltage
Maximum_value_of_L1_2_voltage = 0x0472,   //Maximum value of L1-2 voltage
Maximum_value_of_L2_3_voltage = 0x0474,   //Maximum value of L2-3 voltage
Maximum_value_of_L3_1_voltage = 0x0476,   //Maximum value of L3-1 voltage
Maximum_value_of_L1_voltage_total_harmonic_2 = 0x0478,   //Maximum value of L1 voltage total harmonic (2).
Maximum_value_of_L2_voltage_total_harmonic_2 = 0x047A,   //Maximum value of L2 voltage total harmonic (2).
Maximum_value_of_L3_voltage_total_harmonic_2 = 0x047C,   //Maximum value of L3 voltage total harmonic (2).
Maximum_value_of_L1_current_total_harmonic = 0x047E,   //Maximum value of L1 current total harmonic
Maximum_value_of_L2_current_total_harmonic = 0x0480,   //Maximum value of L2 current total harmonic
Maximum_value_of_L3_current_total_harmonic = 0x0482,   //Maximum value of L3 current total harmonic
Minimum_value_of_total_active_power = 0x0484,   //Minimum value of total active power
Minimum_value_of_total_reactive_power = 0x0486,   //Minimum value of total reactive power
Minimum_value_of_total_apparent_power = 0x0488,   //Minimum value of total apparent power
Minimum_of_the_total_power_factor = 0x048A,   //Minimum of the total power factor
Minimum_value_of_L1_active_power = 0x048C,   //Minimum value of L1 active power
Minimum_value_of_L2_active_power = 0x048E,   //Minimum value of L2 active power
Minimum_value_of_L3_active_power = 0x0490,   //Minimum value of L3 active power
Minimum_value_of_L1_reactive_power = 0x0492,   //Minimum value of L1 reactive power
Minimum_value_of_L2_reactive_power = 0x0494,   //Minimum value of L2 reactive power
Minimum_value_of_L3_reactive_power = 0x0496,   //Minimum value of L3 reactive power
Minimum_value_of_L1_apparent_power = 0x0498,   //Minimum value of L1 apparent power
Minimum_value_of_L2_apparent_power = 0x049A,   //Minimum value of L2 apparent power
Minimum_value_of_L3_apparent_power = 0x049C,   //Minimum value of L3 apparent power
Minimum_of_the_L1_power_factor = 0x049E,   //Minimum of the L1 power factor
Minimum_of_the_L2_power_factor = 0x04A0,   //Minimum of the L2 power factor
Minimum_of_the_L3_power_factor = 0x04A2,   //Minimum of the L3 power factor
Minimum_value_of_L1_current = 0x04A4,   //Minimum value of L1 current
Minimum_value_of_L2_current = 0x04A6,   //Minimum value of L2 current
Minimum_value_of_L3_current = 0x04A8,   //Minimum value of L3 current
Minimum_value_of_neutral_current = 0x04AA,   //Minimum value of neutral current
Minimum_value_of_total_current = 0x04AC,   //Minimum value of total current
Minimum_value_of_L1_voltage = 0x04AE,   //Minimum value of L1 voltage
Minimum_value_of_L2_voltage = 0x04B0,   //Minimum value of L2 voltage
Minimum_value_of_L3_voltage = 0x04B2,   //Minimum value of L3 voltage
Minimum_value_of_L1_2_voltage = 0x04B4,   //Minimum value of L1-2 voltage
Minimum_value_of_L2_3_voltage = 0x04B6,   //Minimum value of L2-3 voltage
Minimum_value_of_L3_1_voltage = 0x04B8,   //Minimum value of L3-1 voltage
Minimum_value_of_L1_voltage_total_harmonic_2 = 0x04BA,   //Minimum value of L1 voltage total harmonic (2).
Minimum_value_of_L2_voltage_total_harmonic_2 = 0x04BC,   //Minimum value of L2 voltage total harmonic (2).
Minimum_value_of_L3_voltage_total_harmonic_2 = 0x04BE,   //Minimum value of L3 voltage total harmonic (2).
Minimum_value_of_L1_current_total_harmonic = 0x0500,   //Minimum value of L1 current total harmonic
Minimum_value_of_L2_current_total_harmonic = 0x0502,   //Minimum value of L2 current total harmonic
Minimum_value_of_L3_current_total_harmonic = 0x0504,   //Minimum value of L3 current total harmonic
Total_import_active_energy = 0x0506,   //Total import active energy.
Total_export_active_energy = 0x0508,   //Total export active energy.
Total_active_Energy_Import_Export = 0x050A,   //Total active Energy (Import + Export).
Net_active_Energy_Import_Export = 0x050C,   //Net active Energy (Import - Export).
Total_import_reactive_energy = 0x050E,   //Total import reactive energy.
Total_export_reactive_energy = 0x0510,   //Total export reactive energy.
Total_reactive_energy_Import_Export = 0x0512,   //Total reactive energy (Import + Export).
Net_reactive_energy_Import_Export = 0x0514,   //Net reactive energy (Import - Export).
Total_apparent_energy = 0x0516,   //Total apparent energy.
The_Ah_of_the_system_current = 0x0518,   //The Ah of the system current
L1_import_active_Energy = 0x051A,   //L1 import active Energy
L2_import_active_Energy = 0x051C,   //L2 import active Energy
L3_import_active_Energy = 0x051E,   //L3 import active Energy
L1_export_active_Energy = 0x0520,   //L1 export active Energy
L2_export_active_Energy = 0x0522,   //L2 export active Energy
L3_export_active_Energy = 0x0524,   //L3 export active Energy
L1_total_active_Energy = 0x0526,   //L1 total active Energy
L2_total_active_Energy = 0x0528,   //L2 total active Energy
L3_total_active_Energy = 0x052A,   //L3 total active Energy
L1_import_reactive_energy = 0x052C,   //L1 import reactive energy
L2_import_reactive_energy = 0x052E,   //L2 import reactive energy
L3_import_reactive_energy = 0x0530,   //L3 import reactive energy
L1_export_reactive_energy = 0x0532,   //L1 export reactive energy
L2_export_reactive_energy = 0x0534,   //L2 export reactive energy
L3_export_reactive_energy = 0x0536,   //L3 export reactive energy
L1_total_reactive_energy = 0x0538,   //L1 total reactive energy
L2_total_reactive_energy = 0x053A,   //L2 total reactive energy
L3_total_reactive_energy = 0x053C,   //L3 total reactive energy
Total_active_energy_of_rate_1 = 0x053E,   //Total active energy of rate 1
Total_active_energy_of_rate_2 = 0x0540,   //Total active energy of rate 2
Total_active_energy_of_rate_3 = 0x0542,   //Total active energy of rate 3
Total_active_energy_of_rate_4 = 0x0544,   //Total active energy of rate 4
Import_active_energy_of_rate_1 = 0x0546,   //Import active energy of rate 1
Import_active_energy_of_rate_2 = 0x0548,   //Import active energy of rate 2
Import_active_energy_of_rate_3 = 0x054A,   //Import active energy of rate 3
Import_active_energy_of_rate_4 = 0x054C,   //Import active energy of rate 4
Export_active_energy_of_rate_1 = 0x054E,   //Export active energy of rate 1
Export_active_energy_of_rate_2 = 0x0550,   //Export active energy of rate 2
Export_active_energy_of_rate_3 = 0x0552,   //Export active energy of rate 3
Export_active_energy_of_rate_4 = 0x0554,   //Export active energy of rate 4
Total_reactive_energy_of_rate_1 = 0x0556,   //Total reactive energy of rate 1
Total_reactive_energy_of_rate_2 = 0x0558,   //Total reactive energy of rate 2
Total_reactive_energy_of_rate_3 = 0x055A,   //Total reactive energy of rate 3
Total_reactive_energy_of_rate_4 = 0x055C,   //Total reactive energy of rate 4
Import_reactive_energy_of_rate_1 = 0x055E,   //Import reactive energy of rate 1
Import_reactive_energy_of_rate_2 = 0x0560,   //Import reactive energy of rate 2
Import_reactive_energy_of_rate_3 = 0x0562,   //Import reactive energy of rate 3
Import_reactive_energy_of_rate_4 = 0x0564,   //Import reactive energy of rate 4
Export_reactive_energy_of_rate_1 = 0x0566,   //Export reactive energy of rate 1
Export_reactive_energy_of_rate_2 = 0x0628,   //Export reactive energy of rate 2
Export_reactive_energy_of_rate_3 = 0x062A,   //Export reactive energy of rate 3
Export_reactive_energy_of_rate_4 = 0x062C,   //Export reactive energy of rate 4
Reactive_energy_in_the_I_quadrant = 0x062E,   //Reactive energy in the I quadrant
Reactive_energy_in_the_II_quadrant = 0x062A,   //Reactive energy in the II quadrant
Reactive_energy_in_the_III_quadrant = 0x062C,   //Reactive energy in the III quadrant
Reactive_energy_in_the_IV_quadrant = 0x062E,   //Reactive energy in the IV quadrant
};

#endif
